name: factions
version: '1.0'
main: com.alfuwu.factions.Factions
api-version: '1.21'

commands:
  faction:
    description: Faction-related commands
    usage: /faction join <id>, /faction list, /faction members <id?>, /faction leader <id?>, /faction invite <factionless player>
    permission: yourplugin.yourcommandpermission