name: factions
version: '1.4'
main: com.alfuwu.factions.Factions
api-version: '1.21'
authors:
  - Alfuwu ;)

commands:
  faction:
    description: Faction-related commands
    usage: /faction join <id>, /faction list, /faction members <id?>, /faction leader <id?>, /faction invite <factionless player>
    permission: factions.normal
  factionmsg:
    description: Message your faction privately
    usage: /factionmsg <message>
    permission: factions.normal
  factiontrust:
    description: Trust players of your faction (GriefPrevention)
    usage: /factiontrust <trust type:access|container|build|all>
    permission: factions.normal
  unfactiontrust:
    description: Untrusts players of your faction (GriefPrevention)
    usage: /unfactiontrust
    permission: factions.normal